service:
    name: justsimpletech

plugins:
    - serverless-bundle
    - serverless-pseudo-parameters

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 256
    stage: ${opt:stage, 'dev'}
    region: eu-west-1
    environment: ${file(.env.yml):}
    iamRoleStatements:
        - ${file(iam/send-mail-iam.yml):SendMailIAM}
        - ${file(iam/feeds-table-iam.yml):FeedsTableIAM}

resources:
    Resources:
        FeedsTable: ${file(resources/feeds-table.yml):FeedsTable}

functions:
    feed:
        handler: src/handlers/feed.handler
        events:
            - http:
                  method: GET
                  path: /feed
                  cors: true
    getWeather:
        handler: src/handlers/get-weather.handler
        events:
            - http:
                  method: POST
                  path: /weather
                  cors: true

    sendMessage:
        handler: src/handlers/send-message.handler
        events:
            - http:
                  method: POST
                  path: /message
                  cors: true
    getFeeds:
        handler: src/handlers/get-feeds.handler
        events:
            - http:
                  method: GET
                  path: /feeds
                  cors: true
    # uploadFeeds:
    #     handler: src/handlers/upload-feeds.handler
    #     events:
    #         - http:
    #               method: POST
    #               path: /feeds/upload
    #               cors: true
custom:
    FeedsTable:
        name: !Ref FeedsTable
        arn: !GetAtt FeedsTable.Arn
    bundle:
        linting: false
